### ISSUE TITLE
which one is the lovelive.app ?

### ISSUE THREAD

**Issue by RennattaSolomon** [kiraio-moe/LoveLive2D#5] opened 2024-07-19 14:51 UTC
![image](https://github.com/user-attachments/assets/afb6917b-01f6-4ce1-89e0-72f0d85748fe)

this is all in the zip file, i dont see lovelive app?

**Comment by kiraio-moe** [comment] 2024-07-19 15:29
Duplicate of #3, please read it.

**Closed** 2024-07-19 15:36 UTC

**Comment by RennattaSolomon** [comment] 2024-07-19 16:23
all i need is to run the lovelive right? 
um.. it didnt work? if tried to run as administrator but still not work
do i have to move the file somewhere or some thing?

**Comment by kiraio-moe** [comment] 2024-07-19 17:29
> all i need is to run the lovelive right? um.. it didnt work? if tried to run as administrator but still not work do i have to move the file somewhere or some thing?

Did you already install either [.NET 6.0 SDK](https://dotnet.microsoft.com/download/dotnet/6.0 ".NET 6.0 SDK") or [.NET 7.0 SDK](https://dotnet.microsoft.com/download/dotnet/7.0 ".NET 7.0 SDK")? If not, install one of them to run the tool.
