### ISSUE TITLE
cant find the .exe

### ISSUE THREAD

**Issue by Najoris** [kiraio-moe/LoveLive2D#12] opened 2024-08-07 20:37 UTC
Hi, 

I wanted to use your free version bc im a student rn and i cant afford the price of live 2 d but ive a project for animation and i want to upgrade my skill (of course when i will able to afford it i will buy it ^^)

You said in your tutorial to launch the .exe file but i dont find it (im maybe blind or maybe you remove it because of issues i dont see) 
 
Have a nice day and thxs for your work and all of that
![Capture d'écran 2024-08-07 223540](https://github.com/user-attachments/assets/99043b2c-dbe4-4508-a398-63b8a43b8994)

**Comment by kiraio-moe** [comment] 2024-08-07 21:56
> Hi,
> 
> I wanted to use your free version bc im a student rn and i cant afford the price of live 2 d but ive a project for animation and i want to upgrade my skill (of course when i will able to afford it i will buy it ^^)
> 
> You said in your tutorial to launch the .exe file but i dont find it (im maybe blind or maybe you remove it because of issues i dont see)
> 
> Have a nice day and thxs for your work and all of that ![Capture d'écran 2024-08-07 223540](https://private-user-images.githubusercontent.com/149301505/355980224-99043b2c-dbe4-4508-a398-63b8a43b8994.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNjc3MDgsIm5iZiI6MTcyMzA2NzQwOCwicGF0aCI6Ii8xNDkzMDE1MDUvMzU1OTgwMjI0LTk5MDQzYjJjLWRiZTQtNDUwOC1hMzk4LTYzYjhhNDNiODk5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QyMTUwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWI3NWY3ZWZiNzZmMDQxODQ4ZDVkZTY3OTdmMmM4MzkxNmRlMzViMTJhNjc5MGQyNGExNGNlNTZhMjZlMDQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u6HYfiGt2-CfCV-DO--CAZvGRP_eErug1kPC2P16KcY)

Duplicate of #3, #5. You're downloading the source code. Download the executables from the Releases: <https://github.com/kiraio-moe/LoveLive2D/releases>  
![image](https://github.com/user-attachments/assets/ad8084bb-e1df-4c99-b40f-464b81781f27)

Also don't forget to install either [.NET 6.0 SDK](https://dotnet.microsoft.com/download/dotnet/6.0 ".NET 6.0 SDK") or [.NET 8 SDK](https://dotnet.microsoft.com/download/dotnet/8.0 ".NET 8.0 SDK").

**Closed** 2024-08-07 21:56 UTC

**Comment by Najoris** [comment] 2024-08-08 08:59
Thanks, i didnt find it bc when we click on the releases link its dont redirect us to the good area 
Have a great day
